PictureWorker/Models/Picture.cs
using System;
using System.Collections.Generic;
using System.Drawing;
using System.Drawing.Imaging;
using System.IO;
using System.Linq;
using System.Web;

namespace PictureWorker.Models
{
    public class Picture
    {   
        public string Name { get; set; }
        public Bitmap Bitmap { get; set; }
        public string Path { get; set; }
        public string ShortPath { get; set; }


        public Picture(Bitmap bm, string name) 
        {
            Bitmap = bm;
            Name = name;
            ShortPath = @"~/Content/Pictures/Edited/" + Name;
        }


        public bool Save(string savePath)
        {
            try
            {
                Bitmap.Save(savePath + Name, ImageFormat.Png);
                Path = savePath + Name;
                return true;
            }
            catch 
            { 
                return false;
            }
        }
    }
}

PictureWorker/Models/PictureEditor.cs
using System;
using System.Collections.Generic;
using System.Drawing;
using System.Drawing.Imaging;
using System.IO;
using System.Linq;
using System.Web;
using System.Reflection;

namespace PictureWorker.Models
{
    public class PictureEditor
    {
        public readonly string pathToSave;
        public readonly string pathToLoad;


        public PictureEditor()
        {
            pathToLoad = "C:\\projects\\test_tasks\\PictureWorker\\PictureWorker\\Content\\Pictures\\Downloads\\";
            if (!Directory.Exists(pathToLoad))
            {
                Directory.CreateDirectory(pathToLoad);
            }

            pathToSave = "C:\\projects\\test_tasks\\PictureWorker\\PictureWorker\\Content\\Pictures\\Edited\\";
            if (!Directory.Exists(pathToSave))
            {
                Directory.CreateDirectory(pathToSave);
            }
        }
        

        private void AddPointToImg(Picture picture, Point point)
        {
            string coordinates = $"{point.X},{point.Y}";

            Font font = new Font("Arial", 12, FontStyle.Bold, GraphicsUnit.Pixel);
            SizeF size = Graphics.FromImage(picture.Bitmap).MeasureString(coordinates, font);
            Point location = new Point(0, 0);

            // Рисуем текст на картинке
            using (Graphics g = Graphics.FromImage(picture.Bitmap))
            {
                g.DrawString(coordinates, font, Brushes.Red, location);
            }
        }


        public List<Picture> CutPicture(string file, int horizontalPartsNumber, int verticalPartsNumber)
        {
            List<Picture> pictures = new List<Picture>();
            int hStep = 1600 / horizontalPartsNumber;
            int vStep = 1200 / verticalPartsNumber;


            Image baseImage = Image.FromFile(file); //основное изображение
            Bitmap baseBitmap = new Bitmap(baseImage, 1600, 1200); //основное изображение в Bitmap

            for (int i = 0; i < verticalPartsNumber; i++)
            {
                for (int j = 0; j < horizontalPartsNumber; j++)
                {
                    
                    Rectangle cropArea = new Rectangle(hStep*j, vStep*i, hStep, vStep); //выбираем часть основнрой картинки для обрезки
                    using (Bitmap target = new Bitmap(cropArea.Width, cropArea.Height))
                    {
                        //перерисовка части основного изображения
                        using (Graphics g = Graphics.FromImage(target))
                        {
                            g.DrawImage(baseBitmap, new Rectangle(0, 0, target.Width, target.Height),
                                cropArea,
                                GraphicsUnit.Pixel);
                        }


                        string name = "new_pic_" + DateTime.Now.ToString("yyyyMMddHHmmssfff") + ".png";
                        Picture newPic = new Picture(target, name);
                        AddPointToImg(newPic, new Point(j * hStep, i * vStep));
                        newPic.Save(pathToSave);
                        pictures.Add(newPic);
                    }
                }
            }
            return pictures;
        }
    }
}

PictureWorker/Controllers/EditorController.cs
using Microsoft.Ajax.Utilities;
using PictureWorker.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Security.Policy;
using System.Threading;
using System.Web;
using System.Web.Mvc;
using System.Xml.Linq;

namespace PictureWorker.Controllers
{
    public class EditorController : Controller
    {
        private PictureEditor editor = new PictureEditor();

        // GET: Editor
        public ActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public ActionResult GetParams()
        {
            return View();
        }

        [HttpPost]
        public ActionResult CutPicture(Uri uri, int height, int width)
        {
            WebClient client = new WebClient();
            string imgName =  "new_pic_" + DateTime.Now.ToString("yyyyMMddHHmmssfff") + ".jpg";
            string savedImg = editor.pathToLoad + imgName;
            client.DownloadFile(uri, savedImg);
            List<Picture> pics = editor.CutPicture(savedImg, height, width);
            return PartialView(pics);
        }
    }
}

PictureWorker/Views/Editor/CutPicture.cshtml
@model IEnumerable<PictureWorker.Models.Picture>

<h2>Разрез:</h2>

<section>
@foreach (PictureWorker.Models.Picture item in Model)
            {
                <img src=@item.ShortPath/>
            }
    <img src="~/Content/Pictures/Downloads/new_pic_20230405060915313.jpg"/>       

</section>

@Scripts.Render("~/bundles/jquery")
<script src='@Url.Content("~/Scripts/jquery.unobtrusive-ajax.js")'></script>

PictureWorker/Views/Editor/GetParams.cshtml
<script>
    function reset() {
        var section = document.getElementById("images");
        section.innerHTML = "";
    }
    
</script>

<h2>AddPicture</h2>
@using (Ajax.BeginForm("CutPicture", "Editor", new AjaxOptions { UpdateTargetId = "images"}))
{
    <table>
        <tr>
            <td>URL изображения:</td>
            <td><input type="text" name="uri" /></td>
        </tr>
        <tr>
            <td>Частей по ширине:</td>
            <td><input type="number" name="width" /></td>
        </tr>
        <tr>
            <td>частей по длине:</td>
            <td><input type="number" name="height" /></td>
        </tr>
        <tr>
            <td></td>
            <td><input type="submit" value="Cut"/></td>
        </tr>
    </table>
}

<div id="images"></div>


@Scripts.Render("~/bundles/jquery")
<script src='@Url.Content("~/Scripts/jquery.unobtrusive-ajax.js")'></script>

PictureWorker/Views/Editor/Index.cshtml
@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

PictureWorker/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<main aria-labelledby="title">
    <h2 id="title">@ViewBag.Title.</h2>
    <h3>@ViewBag.Message</h3>

    <p>Use this area to provide additional information.</p>
</main>

PictureWorker/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<main aria-labelledby="title">
    <h2 id="title">@ViewBag.Title.</h2>
    <h3>@ViewBag.Message</h3>

    <address>
        One Microsoft Way<br />
        Redmond, WA 98052-6399<br />
        <abbr title="Phone">P:</abbr>
        425.555.0100
    </address>

    <address>
        <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
        <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
    </address>
</main>

PictureWorker/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<main>
    <section class="row" aria-labelledby="aspnetTitle">
        <h1 id="title">ASP.NET</h1>
        <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
        <p><a href="https://asp.net" class="btn btn-primary btn-md">Learn more &raquo;</a></p>
    </section>

    <div class="row">
        <section class="col-md-4" aria-labelledby="gettingStartedTitle">
            <h2 id="gettingStartedTitle">Getting started</h2>
            <p>
                ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
                enables a clean separation of concerns and gives you full control over markup
                for enjoyable, agile development.
            </p>
            <p><a class="btn btn-outline-dark" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
        </section>
        <section class="col-md-4" aria-labelledby="librariesTitle">
            <h2 id="librariesTitle">Get more libraries</h2>
            <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
            <p><a class="btn btn-outline-dark" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
        </section>
        <section class="col-md-4" aria-labelledby="hostingTitle">
            <h2 id="hostingTitle">Web Hosting</h2>
            <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
            <p><a class="btn btn-outline-dark" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
        </section>
    </div>
</main>

PictureWorker/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - приложение ASP.NET</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark">
        <div class="container">
            @Html.ActionLink("Имя приложения", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            <button type="button" class="navbar-toggler" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" title="Переключить навигацию" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse d-sm-inline-flex justify-content-between">
                <ul class="navbar-nav flex-grow-1">
                    <li>@Html.ActionLink("Домашняя страница", "Index", "Home", new { area = "" }, new { @class = "nav-link" })</li>
                    <li>@Html.ActionLink("Информация", "About", "Home", new { area = "" }, new { @class = "nav-link" })</li>
                    <li>@Html.ActionLink("Связаться", "Contact", "Home", new { area = "" }, new { @class = "nav-link" })</li>
                </ul>
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - мое приложение ASP.NET</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>